### ISSUE TITLE
aaa.html is not really html. It includes JavaScript

### ISSUE THREAD

**Issue by IceCereal** [Benricheson101/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#56]
This is quite a pedantic issue, but I believe it's important for the sake of maintaining the integrity of the repository.

`aaa.html` includes
```html
<script>
      setInterval(() => document.getElementById("aaaaaaaaaa").innerHTML += "a", 1)
</script>
```
which is JavaScript code. If we're to abide the repository's description, which at the time of writing is `Contributor note: code must spam "a" all on one line, there must not be any duplicate languages`, then there is a duplicate language in `aaa.html`, in some sense.

I have 2 proposals:

1. If `aaa.xml` can have 1800000 a's printed, then why can't `aaa.html`? It seems like a simple enough fix.
2. This is slightly more complex. If CSS were to be included, one possibility is to use keyframes and the content modifier to add an `a` to the content with every %.
```css
@keyframes changeLetter {
  0% {
    content: "A";
  }
  1% {
    content: "AA";
  }
  2% {
    content: "AAA";
  }
  ....
}
```
Although not an elegant solution, it does manage to remove the JavaScript tag that the current file has.
